'use strict';
(() => {
const $ = id => document.getElementById(id);
const canvas = $('game'), ctx = canvas.getContext('2d');
const MAP=window.CSICSO_MAP;
const W=MAP.width,H=MAP.height,SAVE='csicso-ork-level1-v2';
let width=innerWidth,height=innerHeight,dpr=1,running=false,dialog=null,keys={},camera={x:0,y:0},state,near=null,toastTime=0,last=0,clock=0,saveTimer=0,sound=false,audio;
let seed=91627; const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const P=MAP.byId;
const locations=MAP.sites.map(l=>({...l,anchorX:l.x,anchorY:l.y,y:l.y+({parliament:46,shop:49,culture:47,office:50,well:39,castle:68,school:25,restaurant:92}[l.id]||0)}));
Object.assign(locations.find(l=>l.id==='lion'),MAP.point([885,550]));
Object.assign(locations.find(l=>l.id==='fishponds'),MAP.point([1134,514]));
const site=id=>locations.find(l=>l.id===id);
const buildings=[];
function building(id,w,h,dx=-w/2,dy=-h+20,type=id){const l=P[id];buildings.push({x:l.x+dx,y:l.y+dy,w,h,type,id});}
building('shop',240,88,-187,-78);
building('culture',145,86);
building('office',180,68,-185,-40);
building('castle',242,126,-121,-104);
building('school',180,90,-150,-120);
building('restaurant',150,65,-75,0);
for(const [x,y] of [[1667,654],[1708,622],[1728,649],[1770,613],[1797,573],[1595,761],[1645,800],[1680,749],[1500,724]]){const q=MAP.point([x,y]);buildings.push({x:q.x-45,y:q.y-67,w:90,h:67,type:'house'});}
const solid=buildings.map(b=>({x:b.x-4,y:b.y-2,w:b.w+8,h:b.h+4}));
for(const id of MAP.shelters){const q=P[id];solid.push({x:q.x-45,y:q.y-23,w:89,h:38});}
solid.push({x:P.well.x-20,y:P.well.y-27,w:40,h:31});
const bins=MAP.bins;
const groundItems=[];
function item(type,x,y){groundItems.push({id:groundItems.length,type,x,y});}
for(const id of ['parliament','park','shop','square','restaurant','shelter-west','shelter-east','lion','vineyard','fishponds']){const q=site(id);item('bottle',q.x+46,q.y+24);item('butt',q.x-30,q.y+28);}
const lionTrail=MAP.point([860,584]);item('boost',lionTrail.x+35,lionTrail.y);item('bottle',lionTrail.x+10,lionTrail.y+80);
function segmentDistance(x,y,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],n=dx*dx+dy*dy;const t=n?Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/n)):0;return Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy);}
function inside(x,y,points){let yes=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
function onRoad(x,y,extra=0){return MAP.roads.some(r=>r.p.slice(1).some((b,i)=>segmentDistance(x,y,r.p[i],b)<r.width/2+extra));}
function inWater(x,y){if(onRoad(x,y,5))return false;return MAP.waters.some(w=>inside(x,y,w.p))||MAP.stream.slice(1).some((b,i)=>segmentDistance(x,y,MAP.stream[i],b)<9);}
// Loose objects may shift a few steps to keep the annotated entrances and paths usable.
for(const o of [...bins,...groundItems]){if(!blocked(o.x,o.y))continue;let found=false;for(let r=20;r<=160&&!found;r+=15)for(let a=0;a<Math.PI*2;a+=Math.PI/8){const x=o.x+Math.cos(a)*r,y=o.y+Math.sin(a)*r;if(!blocked(x,y)){o.x=x;o.y=y;found=true;break;}}}
const trees=[],tufts=[],pebbles=[];
function occupied(x,y){return inWater(x,y)||solid.some(r=>x>r.x-45&&x<r.x+r.w+45&&y>r.y-45&&y<r.y+r.h+45)||locations.some(l=>Math.hypot(x-l.x,y-l.y)<85)||groundItems.some(i=>Math.hypot(x-i.x,y-i.y)<40)||bins.some(i=>Math.hypot(x-i.x,y-i.y)<37);}
const pitch=P.football;
for(let i=0;i<1000;i++){const x=60+random()*(W-120),y=60+random()*(H-120);const forest=MAP.zones.some(z=>z.name!=='Ham'&&inside(x,y,z.p));if(!forest&&random()>.18)continue;if(!onRoad(x,y,25)&&!occupied(x,y)&&!(Math.abs(x-pitch.x)<120&&Math.abs(y-pitch.y)<100))trees.push({x,y,s:(forest?.8:.6)+random()*.55,c:forest?2:Math.floor(random()*2)});}
for(let i=0;i<2700;i++)tufts.push({x:random()*W,y:random()*H,s:2+random()*5,c:random()});
for(let i=0;i<1100;i++){const x=random()*W,y=random()*H;if(onRoad(x,y))pebbles.push({x,y,s:1+random()*4});}
for(const t of trees)solid.push({x:t.x-9,y:t.y-8,w:18,h:16});
const crest=new Image();crest.src='assets/csicso-cimer.jpg';
function fresh(){return {x:site('parliament').x+30,y:site('parliament').y+35,bottles:0,cash:0,butts:0,paper:1,cigs:0,wine:0,delivered:0,capacity:12,bike:false,bikeX:site('parliament').x+88,bikeY:site('parliament').y+40,energy:100,boost:0,sober:0,time:0,taken:[],bins:{},rolled:0,trade:false,castle:false,won:false,steps:0,total:0};}
function validSave(s){return s&&Number.isFinite(s.x)&&Number.isFinite(s.y)&&s.x>=0&&s.x<=W&&s.y>=0&&s.y<=H&&Array.isArray(s.taken)&&s.bins&&['cash','bottles','butts','paper','wine','delivered','energy','time'].every(k=>Number.isFinite(s[k])&&s[k]>=0);}
function load(){try{const current=JSON.parse(localStorage.getItem(SAVE));if(validSave(current))return Object.assign(fresh(),current);const old=JSON.parse(localStorage.getItem('csicso-ork-level1-v1'));if(validSave(old)){const n=Object.assign(fresh(),old),spawn=fresh();Object.assign(n,{x:spawn.x,y:spawn.y,bike:false,bikeX:spawn.bikeX,bikeY:spawn.bikeY,taken:[],bins:{},mapMigrated:true});return n;}return null;}catch{return null;}}
function save(){if(!state||!running||!$('start').hidden)return;try{localStorage.setItem(SAVE,JSON.stringify(state));$('saveStatus').textContent='Mentve a böngészőben';}catch{$('saveStatus').textContent='A mentés itt nem elérhető';}}
function start(s){state=s||fresh();running=true;dialog=null;keys={};$('start').hidden=true;$('hud').hidden=false;$('modalBackdrop').hidden=true;camera.x=state.x-width/2;camera.y=state.y-height/2;updateHUD();save();toast('Egy műszak. Három csucsó. Indulás!');}
function money(v){return (v/100).toLocaleString('hu-HU',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastTime=3.4;}
function beep(freq=540){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.16);}catch{}}
function updateHUD(){if(!state)return;$('bottles').textContent=state.bottles+' / '+state.capacity;$('cash').textContent=money(state.cash).replace(' €','');$('butts').textContent=state.butts;$('wine').textContent=state.wine;$('delivered').textContent=state.delivered+' / 3 csucsó leszállítva';$('progress').style.width=(state.delivered/3*100)+'%';$('bikeTag').hidden=!state.bike;
 $('questText').textContent=state.won?'A határozat elfogadva! A falut továbbra is szabadon bejárhatod.':state.wine?'Vidd a csucsót a Parlamenthez, és add le az ülésre.':state.cash>=75?'Megvan a pénz: a Jednotában 0,75 € egy csucsó.':state.bottles>=5?'Irány a Jednota! Öt palackból már kijön egy csucsó.':'Gyűjts palackot, és váltsd vissza a Jednotában.';
 $('sidequest').textContent=state.rolled?'✓ A sodrás kész. Jutkánál elcserélheted apróra.':'Mellékküldetés: 5 csikkből sodrás a Parlamentnél.';
 $('buff').hidden=!(state.boost>0||state.sober>0);$('buff').textContent=state.boost>0?'✦ ORKERŐ · '+Math.ceil(state.boost)+' mp · gyorsaság + sérthetetlenség':'JÓZANODÁS… '+Math.ceil(state.sober)+' mp';
}
function showDialog(kind,title,eyebrow,html,actions=[]){dialog=kind;keys={};$('modal').classList.toggle('wide',kind==='map');$('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalBody').innerHTML=html;$('modalActions').replaceChildren();for(const a of actions){const b=document.createElement('button');b.innerHTML=a.label;b.className=a.primary?'primary':'';b.disabled=!!a.disabled;b.onclick=a.run;$('modalActions').append(b);}$('modalBackdrop').hidden=false;$('interact').hidden=true;setTimeout(()=>$('closeModal').focus(),0);}
function close(){dialog=null;keys={};$('modalBackdrop').hidden=true;save();updateHUD();}
function station(id){
 const notes={office:['Községi hivatal','A Lion vendéglő és a kultúrház között álló községi hivatal.'],square:['A Főtér','A Jednota és a Hétvezér park közötti törzshely. A tér és a szemközti iskola körül sok a kuka.'],school:['Az iskola','A Főtér túloldalán jársz. A kapu és a buszmegálló mellett keress palackot. Az épület helye egyelőre közelítés a leírás alapján.'],restaurant:['Lion vendéglő','A falubeli vendéglő előtt is vannak kukák. A Lion-rengeteg innen nyugatra, a Hami úton érhető el.'],football:['Focipálya','A kastélyparkból az erdei ösvény és a Csörgő híd vezet ide.'],bridge:['Csörgő híd','A kastélypark és a focipálya közötti erdei kapcsolat. A híd pontos helye egyelőre közelítés.'],smallbridge:['Kishíd','A térképen külön X-szel megjelölt kis híd, a kultúrháztól keletre.'],vineyard:['Szőlős kertek','A Lion bejárata és a Hami út mellett sorakoznak a szőlők.'],fishponds:['Halastavak','A Hami úttól északra egymás fölött húzódó tavak. A rabsickodós történetszál még készül.'],ham:['Ham','A halastavaktól délre elterülő nádas mocsár.'],birdwatch:['Madárles','A falu keleti szélén álló megfigyelőhely.']};
 if(notes[id]){showDialog(id,notes[id][0],'CSICSÓ HELYSZÍNEI','<p>'+notes[id][1]+'</p>',[{label:'Tovább →',primary:true,run:close}]);return;}
 if(id.startsWith('shelter-')){showDialog(id,'Ideiglenes kiülő','NEM A PARLAMENT','<p>Itt is megpihenhetnek az orkok, de az esti ellátmányt a Notorik parkban lévő Parlamenthez kell vinni.</p>',[{label:'Megpihenek',primary:true,run:()=>{state.energy=100;close();toast('Pihenő vége. A Parlament a kastélytó mellett vár.');}}]);return;}
 if(id==='shop')showDialog('shop','COOP Jednota','VISSZAVÁLTÁS & BEVÁSÁRLÁS',`<p>A palackautomata készen áll. A csucsó a legalsó polcon vár.</p><div class="balance">${money(state.cash)}</div><div class="stock"><span>${state.bottles} palack</span><span>${state.wine} csucsó</span><span>${state.paper} cigipapír</span></div>`,[
 {label:`Palackok visszaváltása <small>+${money(state.bottles*15)}</small>`,primary:true,disabled:!state.bottles,run:()=>{const n=state.bottles;state.cash+=n*15;state.total+=n;state.bottles=0;beep(780);save();updateHUD();station('shop');toast(n+' palack beváltva: '+money(n*15));}},
 {label:'Egy üveg CSUCSÓ <small>0,75 €</small>',disabled:state.cash<75,run:()=>{state.cash-=75;state.wine++;beep();save();updateHUD();station('shop');toast('Egy csucsó a szatyorban. A Parlament vár!');}},
 {label:'Cigipapír <small>0,15 €</small>',disabled:state.cash<15,run:()=>{state.cash-=15;state.paper++;save();updateHUD();station('shop');}},
 {label:state.capacity>12?'Nagy szatyor megvéve ✓':'Nagy szatyor · 20 férőhely <small>0,60 €</small>',disabled:state.cash<60||state.capacity>12,run:()=>{state.cash-=60;state.capacity=20;save();updateHUD();station('shop');}}
 ]);
 if(id==='parliament')showDialog('parliament','Ülésezik a Parlament','A KIÜLŐ · FŐHADISZÁLLÁS',`<p>„Napirend előtt: ki hozta az ellátmányt?”<br>Az esti üléshez <strong>3 csucsó</strong> kell. Eddig <strong>${state.delivered}</strong> érkezett meg.</p><div class="stock"><span>${state.wine} csucsó</span><span>${state.butts} csikk</span><span>${state.paper} papír</span><span>${state.cigs} sodrás</span></div>`,[
 {label:'Csucsó leadása az ülésre <small>'+Math.min(state.wine,3-state.delivered)+' üveg</small>',primary:true,disabled:!state.wine||state.delivered>=3,run:()=>{const n=Math.min(state.wine,3-state.delivered);state.delivered+=n;state.wine-=n;beep(880);if(state.delivered>=3){state.won=true;save();updateHUD();win();}else{save();updateHUD();station('parliament');toast('A Parlament elégedett. Még '+(3-state.delivered)+' csucsó kell.');}}},
 {label:'Parlamenti sodrás <small>5 csikk + 1 papír</small>',disabled:state.butts<5||state.paper<1,run:()=>{state.butts-=5;state.paper--;state.cigs++;state.rolled++;beep(440);save();updateHUD();station('parliament');toast('Kész a sodrás, bekerült a szatyorba.');}},
 {label:'Rövid üldögélés <small>+ erőnlét</small>',run:()=>{state.energy=100;close();toast('Jegyzőkönyv: a pihenő eredményes volt.');}}
 ]);
 if(id==='culture')showDialog('culture','Kultúrház','A FALU TALÁLKOZÓHELYE','<p>A kultúrházhoz érkeztél. Innen a Kishíd felé is továbbindulhatsz.</p>',[{label:'Tovább →',primary:true,run:close}]);
 if(id==='well'){state.energy=100;state.boost=0;state.sober=0;updateHUD();save();toast('Friss víz! Erőnlét feltöltve, minden löttyhatás megszűnt.');beep(900);}
 if(id==='park')showDialog('park','Hétvezér park','HÉT SZOBOR · SOK TÖRTÉNET',`<p>Hét faragott alak nézi a falut. A padok körül rendszeresen maradnak palackok és csikkek.</p><p>A Hami út nyugat felé a Lionba vezet. A biciklit az erdő sűrűjében érdemes letenni.</p>`,[{label:'Tovább keresgélek →',primary:true,run:close}]);
 if(id==='castle')showDialog('castle','A kastély kertje','ZICHY–KÁLNOKY-KASTÉLY',`<p>„Tegnap rendezvény volt. Ha összeszeditek az üres palackokat, vihetitek őket.”</p><p>A kertész egyszer ad egy hatpalackos csomagot. ${state.castle?'Ezt már átvetted.':'Legalább hat szabad hely kell a szatyorban.'}</p>`,[{label:'A hat palack átvétele',primary:true,disabled:state.castle||state.capacity-state.bottles<6,run:()=>{state.castle=true;state.bottles+=6;save();updateHUD();close();toast('A kastélykertből +6 palack. Köszönik a rendrakást!');}}]);
 if(id==='lion')showDialog('lion','Lion-rengeteg','CSICSÓ VADONJA',`<p>Fűzfák, nád és mozdulatlan víz. A falusi ösvény itt vadonná változik.</p><p>A világító <strong>Gyanús lötty</strong> 20 másodpercre gyorsaságot és sérthetetlenséget ad. Utána 6 másodperc józanodás következik. Mesebeli erősítő.</p><p>Az erdőben gyalog gyorsabb, mint a bringát tolva. A kóbor vaddisznót kerüld ki!</p>`,[{label:'Be a rengetegbe →',primary:true,run:close}]);
}
function win(){showDialog('win','A határozat elfogadva!','PÁLYA TELJESÍTVE',`<div class="result">3 / 3<small>csucsó az asztalon</small></div><p>A Parlament ellátása biztosított. A képviselők egyhangúlag megszavazták: holnap is lesz ülés.</p><div class="stock"><span>${Math.floor(state.time/60)} p ${Math.floor(state.time%60)} mp</span><span>${state.total} beváltott palack</span><span>${state.rolled} sodrás</span></div>`,[{label:'Maradok még a faluban →',primary:true,run:close},{label:'Új műszak',run:resetDialog}]);}
function resetDialog(){showDialog('reset','Új műszak?','ELÖLRŐL KEZDÉS','<p>A jelenlegi helyi mentést felváltja az új játék.</p>',[{label:'Igen, induljon új játék',primary:true,run:()=>start(fresh())},{label:'Vissza',run:close}]);}
function pause(){showDialog('pause','Egy kis szünet','A FALU MEGVÁR',`<div class="helpgrid"><kbd>W A S D / ↑ ↓ ← →</kbd><span>Mozgás</span><kbd>E / Szóköz</kbd><span>Gyűjtés, kukázás, beszélgetés</span><kbd>B</kbd><span>Bringára szállás / leszállás</span><kbd>Shift</kbd><span>Futás, amíg tart az erőnlét</span><kbd>M</kbd><span>Falutérkép</span><kbd>Esc</kbd><span>Szünet / ablak bezárása</span></div><p>A sötétzöld kukák két palackot és egy csikket adnak; 45 játékbeli másodperc után újra kutathatók. Gyűjtéshez szállj le a bringáról. A játék automatikusan ment ebben a böngészőben.</p><p>Telefonon az iránygombokkal mozoghatsz. A hang külön kapcsolható.</p>`,[{label:'Vissza a faluba →',primary:true,run:close},{label:'Új játék',run:resetDialog}]);}
function bike(){if(!running||dialog)return;if(state.bike){state.bike=false;const spot=[[27,8],[-27,8],[0,27],[0,-27],[0,0]].find(([x,y])=>!blocked(state.x+x,state.y+y));state.bikeX=state.x+spot[0];state.bikeY=state.y+spot[1];toast('Bringa letámasztva.');}else if(dist(state,{x:state.bikeX,y:state.bikeY})<90){state.bike=true;toast('Nyolcas Expressz indul! B: leszállás.');}else{toast('Menj közelebb a bringádhoz. A térképen kék jel mutatja.');}updateHUD();save();}
function nearby(){let best=null,score=Infinity;const consider=(o,r)=>{const d=dist(state,o);if(d<r&&d<score){best=o;score=d;}};for(const i of groundItems)if(!state.taken.includes(i.id))consider({...i,kind:'item'},47);bins.forEach((b,i)=>consider({...b,id:i,kind:'bin'},65));for(const l of locations)consider({...l,kind:'station'},85);if(!state.bike)consider({x:state.bikeX,y:state.bikeY,kind:'bike'},65);return best;}
function interact(){if(!running||dialog)return;near=nearby();if(!near)return;const n=near;if(n.kind==='bike'){bike();return;}if(state.bike){toast('Előbb szállj le a bringáról: B.');return;}
 if(n.kind==='station'){station(n.id);return;}
 if(n.kind==='item'){if(n.type==='bottle'){if(state.bottles>=state.capacity){toast('Tele a szatyor! Váltsd be a palackokat a Jednotában.');return;}state.bottles++;toast('+1 palack · 0,15 €');}else if(n.type==='butt'){state.butts++;toast('+1 csikk · '+state.butts+'/5 a következő sodráshoz');}else{state.boost=20;state.sober=0;toast('GYANÚS LÖTTY! 20 mp orkerő.');}state.taken.push(n.id);beep(n.type==='boost'?1000:620);}
 if(n.kind==='bin'){if(n.type==='brown'){toast('BIO: erjedt gyümölcs. Ürítés kéthetente szerdán; a feldolgozás még készül.');return;}const ready=state.bins[n.id]||0;if(state.time<ready){toast('Már átnézted. Új zsákmány '+Math.ceil(ready-state.time)+' mp múlva.');return;}const space=state.capacity-state.bottles;if(space<1){toast('Tele a szatyor! Irány a Jednota.');return;}const amount=Math.min(2,space);state.bottles+=amount;state.butts++;state.bins[n.id]=state.time+45;toast('Kukazsákmány: +'+amount+' palack, +1 csikk.');beep(400);}
 updateHUD();save();
}
function map(){showDialog('map','Csicsó, ork szemmel','FALUTÉRKÉP','<canvas id="mapCanvas" class="mapcanvas" width="760" height="520" aria-label="Térkép a helyszínekkel és a játékos helyzetével"></canvas><div class="legend"><span>● Arany: helyszínek</span><span>● Fehér: te</span><span>● Kék: bringád</span><span>■ Zöld: kukák</span></div><p style="font-size:11px">A jelölt térképed alapján. A falu léptéke nagyított; az iskola és a Csörgő híd helye közelítés.</p>');drawMap();}
function drawMap(){const c=$('mapCanvas'),g=c.getContext('2d'),sx=c.width/W,sy=c.height/H;g.fillStyle='#82915a';g.fillRect(0,0,c.width,c.height);g.save();g.scale(sx,sy);g.drawImage(floor,0,0);for(const b of buildings){g.fillStyle=b.type==='shop'?'#e5d5b3':'#ac8c59';g.fillRect(b.x,b.y,b.w,b.h);}for(const b of bins){g.fillStyle=b.type==='recycling'?({paper:'#4a88d1',plastic:'#e2bd4c',glass:'#52845b'}[b.material]):b.type==='blue'?'#5b9bda':b.type==='brown'?'#a87647':'#dbe3bc';g.fillRect(b.x-8,b.y-8,16,16);}g.restore();const labels=new Set(['parliament','shop','culture','well','park','castle','lion','football','ham','vineyard','fishponds','school','square','restaurant','bridge','office']);const offsets={parliament:[77,-8],castle:[-42,-6],park:[67,9],shop:[-36,8],school:[-65,-9],culture:[-10,14],well:[43,0],football:[0,-15],square:[45,-16],restaurant:[-68,15],office:[-84,16],bridge:[-45,-16]};for(const l of locations){const x=l.anchorX*sx,y=l.anchorY*sy;g.fillStyle='#eec264';g.beginPath();g.arc(x,y,3,0,Math.PI*2);g.fill();if(!labels.has(l.id))continue;const[dx,dy]=offsets[l.id]||[0,-12];g.strokeStyle='#eec26477';g.lineWidth=1;g.beginPath();g.moveTo(x,y);g.lineTo(x+dx,y+dy);g.stroke();g.font='bold 10px Segoe UI';g.textAlign='center';g.lineWidth=3;g.strokeStyle='#243e30';const name=l.id==='parliament'?'Parlament':l.name;g.strokeText(name,x+dx,y+dy);g.fillStyle='#fff3d4';g.fillText(name,x+dx,y+dy);}g.fillStyle='#8ed7e6';g.fillRect((state.bike?state.x:state.bikeX)*sx-3,(state.bike?state.y:state.bikeY)*sy-3,6,6);g.fillStyle='#fff';g.strokeStyle='#263928';g.lineWidth=2;g.beginPath();g.arc(state.x*sx,state.y*sy,5,0,Math.PI*2);g.fill();g.stroke();text(g,'É ↑',c.width-25,28,16);text(g,'NYUGAT · LION',110,c.height-15,10);text(g,'KELET · CSICSÓ',c.width-110,c.height-15,10);}
function blocked(x,y){const r=12;if(x<25||y<25||x>W-25||y>H-25)return true;if(inWater(x,y)||inWater(x-r,y)||inWater(x+r,y)||inWater(x,y-r)||inWater(x,y+r))return true;return solid.some(b=>x+r>b.x&&x-r<b.x+b.w&&y+r>b.y&&y-r<b.y+b.h);}
const boar={x:lionTrail.x+60,y:lionTrail.y+140,cooldown:0};
function update(dt){clock+=dt;if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');}if(!running||dialog)return;state.time+=dt;let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const moving=dx||dy,forest=inside(state.x,state.y,MAP.zones[0].p);let speed=state.bike?(forest?100:245):145;
 if(keys.shift&&state.energy>2&&!state.bike&&moving){speed=215;state.energy=Math.max(0,state.energy-dt*20);}else state.energy=Math.min(100,state.energy+dt*12);
 if(state.boost>0){speed*=1.7;state.boost=Math.max(0,state.boost-dt);if(state.boost===0){state.sober=6;toast('JÓZANODÁS! Kicsit lassabban…');}}else if(state.sober>0){speed*=.62;state.sober=Math.max(0,state.sober-dt);}
 if(moving){const n=Math.hypot(dx,dy);dx/=n;dy/=n;state.facing=dx<0?-1:dx>0?1:state.facing||1;state.steps+=dt*speed/22;const nx=state.x+dx*speed*dt,ny=state.y+dy*speed*dt;if(!blocked(nx,state.y))state.x=nx;if(!blocked(state.x,ny))state.y=ny;}
 boar.x=lionTrail.x+90+Math.sin(state.time*.35)*35;boar.y=lionTrail.y+145+Math.cos(state.time*.45)*30;boar.cooldown=Math.max(0,boar.cooldown-dt);if(dist(state,boar)<33&&boar.cooldown===0&&!state.boost){boar.cooldown=5;if(state.bottles){state.bottles--;toast('A vaddisznó fellökött! −1 palack.');}else toast('Morcos vaddisznó! Kerüld ki.');beep(150);}
 near=nearby();$('interact').hidden=!near;if(near){let text=near.kind==='station'?near.name:near.kind==='bike'?'Nyolcas Expressz':near.kind==='bin'?near.type==='recycling'?('Szelektív · '+({paper:'papír',plastic:'műanyag',glass:'üveg'}[near.material])):near.type==='brown'?'Barna kuka · BIO':near.type==='blue'?'Kék kuka':(state.time<(state.bins[near.id]||0)?'Kuka · '+Math.ceil(state.bins[near.id]-state.time)+' mp':'Kuka átkutatása'):near.type==='bottle'?'Visszaváltható palack':near.type==='butt'?'Elhagyott csikk':'Gyanús lötty';$('interactText').textContent=state.bike?'Szállj le: B · '+text:text;}
 let zone='Csicsó utcái',closest=300;for(const l of locations){const d=dist(state,l);if(d<closest){closest=d;zone=l.name;}}if(forest)zone='Lion-rengeteg';$('zoneName').textContent=zone;
 const tx=Math.max(0,Math.min(W-width,state.x-width/2)),ty=Math.max(0,Math.min(H-height,state.y-height/2));camera.x+=(tx-camera.x)*Math.min(1,dt*7);camera.y+=(ty-camera.y)*Math.min(1,dt*7);saveTimer+=dt;if(saveTimer>8){save();saveTimer=0;}updateHUD();}
// All playfield art is drawn as independent, depth-sorted 2D objects.
function rect(g,x,y,w,h,fill,stroke){g.fillStyle=fill;g.fillRect(x,y,w,h);if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.strokeRect(x,y,w,h);}}
function poly(g,points,fill,stroke){g.beginPath();points.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();g.fillStyle=fill;g.fill();if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.stroke();}}
function ellipse(g,x,y,rx,ry,fill){g.fillStyle=fill;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill();}
function text(g,str,x,y,size=12,color='#fff0cf',align='center'){g.font=`bold ${size}px "Segoe UI",sans-serif`;g.textAlign=align;g.fillStyle=color;g.fillText(str,x,y);}
function label(g,str,x,y){g.font='bold 12px Segoe UI';const w=g.measureText(str).width+24;g.fillStyle='#20372de8';g.beginPath();g.roundRect(x-w/2,y-18,w,27,6);g.fill();text(g,str,x,y,12);}
function strokePath(g,p,color,width){g.strokeStyle=color;g.lineWidth=width;g.lineJoin='round';g.lineCap='round';g.beginPath();p.forEach((q,i)=>i?g.lineTo(...q):g.moveTo(...q));g.stroke();}
function drawRoads(g){for(const r of MAP.roads){strokePath(g,r.p,'#7d805755',r.width+7);strokePath(g,r.p,r.width<35?'#b6ad83':'#c9bb99',r.width);}}
const floor=document.createElement('canvas');floor.width=W;floor.height=H;const f=floor.getContext('2d');
function ground(){f.fillStyle='#8b9864';f.fillRect(0,0,W,H);for(const z of MAP.zones)poly(f,z.p,z.color);for(const t of tufts){f.strokeStyle=t.c>.7?'#b3bc7955':'#4f704b55';f.lineWidth=1;f.beginPath();f.moveTo(t.x-2,t.y);f.lineTo(t.x-3,t.y-t.s);f.moveTo(t.x,t.y);f.lineTo(t.x+2,t.y-t.s-2);f.stroke();}
for(const w of MAP.waters){poly(f,w.p,'#567f7a','#365f59');f.save();f.beginPath();w.p.forEach((q,i)=>i?f.lineTo(...q):f.moveTo(...q));f.closePath();f.clip();for(let i=0;i<100;i++){const x=random()*W,y=random()*H;if(inside(x,y,w.p)){strokePath(f,[[x,y],[x+15,y]],'#9cc4ad66',2);ellipse(f,x-6,y+4,5,2,'#9aae6d');}}f.restore();}
strokePath(f,MAP.stream,'#6f9890',17);drawRoads(f);for(const p of pebbles)ellipse(f,p.x,p.y,p.s,1,'#8d806241');
const sq=P.square;ellipse(f,sq.x,sq.y,85,53,'#d4c5a3');for(let x=-70;x<80;x+=22)strokePath(f,[[sq.x+x,sq.y-38],[sq.x+x,sq.y+38]],'#9e967b44',1);
const pt=P.football;rect(f,pt.x-110,pt.y-72,220,144,'#679359');f.strokeStyle='#d2dfb0';f.lineWidth=2;f.strokeRect(pt.x-101,pt.y-64,202,128);strokePath(f,[[pt.x,pt.y-64],[pt.x,pt.y+64]],'#d2dfb0',2);f.beginPath();f.arc(pt.x,pt.y,27,0,Math.PI*2);f.stroke();f.strokeRect(pt.x-105,pt.y-25,21,50);f.strokeRect(pt.x+84,pt.y-25,21,50);
for(const id of ['bridge','smallbridge']){const q=P[id];rect(f,q.x-38,q.y-19,76,38,'#a18152','#66563a');for(let x=-35;x<36;x+=8)strokePath(f,[[q.x+x,q.y-17],[q.x+x,q.y+17]],'#725d3c',2);strokePath(f,[[q.x-39,q.y-21],[q.x+39,q.y-21]],'#c3a56a',4);strokePath(f,[[q.x-39,q.y+21],[q.x+39,q.y+21]],'#c3a56a',4);}
const v=P.vineyard;for(let row=0;row<8;row++)for(let col=0;col<8;col++){const x=v.x-70+col*22,y=v.y-70+row*21;rect(f,x,y,3,13,'#786649');ellipse(f,x,y-2,9,5,'#526f42');}
const ham=MAP.zones.find(z=>z.name==='Ham');for(let i=0;i<320;i++){const x=850+random()*750,y=1000+random()*450;if(inside(x,y,ham.p)){strokePath(f,[[x,y],[x-3,y-19]],'#586d45',2);ellipse(f,x-3,y-20,2,5,'#8c7b44');}}
for(const id of MAP.shelters){const q=P[id];rect(f,q.x-75,q.y-57,155,92,'#b9b89e');}
}ground();
function shadow(g,x,y,w=25){ellipse(g,x+8,y+4,w,w*.3,'#1c342c35');}
function drawTree(g,t){const{x,y,s}=t;g.save();g.translate(x,y);g.scale(s,s);shadow(g,0,0,36);rect(g,-7,-51,14,53,'#725c3d','#4d4c31');poly(g,[[-6,-27],[-23,-47],[-19,-51],[1,-34]],'#725c3d');const colors=[['#476443','#65804d','#829657'],['#5a713e','#83934d','#a3a759'],['#345b43','#4c7650','#6a8b58']][t.c];ellipse(g,0,-76,42,37,colors[0]);ellipse(g,-22,-67,27,29,colors[0]);ellipse(g,23,-75,30,29,colors[1]);ellipse(g,-10,-91,29,26,colors[1]);ellipse(g,-15,-98,20,13,colors[2]);ellipse(g,16,-89,17,12,colors[2]);g.restore();}
function windowBox(g,x,y,w,h){rect(g,x,y,w,h,'#324843','#ebdcba');rect(g,x+3,y+3,w-6,h/3,'#729087');rect(g,x+w/2-1,y,2,h,'#dbcba7');}
function drawOffice(g,b){
 const x=b.x,y=b.y-28,w=b.w,h=b.h+28;
 shadow(g,x+w/2,y+h,w*.6);rect(g,x,y,w,h,'#e2e0d4','#969585');
 for(const xx of [x+7,x+109])rect(g,xx,y+34,62,38,'#b45549');
 for(const xx of [x+12,x+48,x+112,x+150])windowBox(g,xx,y+35,17,38);
 poly(g,[[x-9,y+6],[x+22,y-43],[x+w-21,y-43],[x+w+10,y+6]],'#aa6553','#614b40');
 for(let yy=y-36;yy<y+6;yy+=7){g.strokeStyle='#d7947266';g.lineWidth=2;g.beginPath();g.moveTo(x+18,yy);g.lineTo(x+w-15,yy);g.stroke();}
 rect(g,x+73,y+20,30,h-20,'#b85b4c');windowBox(g,x+78,y+44,21,h-46);
 poly(g,[[x+65,y+29],[x+74,y+9],[x+103,y+9],[x+113,y+29]],'#a55d4a','#5d4a3c');
 rect(g,x+74,y+h,32,5,'#7b827c');rect(g,x+71,y+h+5,38,5,'#999e92');
 text(g,'OBECNÝ ÚRAD',x+36,y+25,7,'#394847');text(g,'KÖZSÉGI HIVATAL',x+142,y+25,7,'#394847');
 for(const [j,c] of ['#426c9f','#e1e1d4','#b95248'].entries()){rect(g,x+w-16+j*8,y+20,1,23,'#848c80');poly(g,[[x+w-16+j*8,y+20],[x+w-7+j*8,y+25],[x+w-8+j*8,y+39],[x+w-16+j*8,y+34]],c);}
 for(const [a,z]of [[x-8,x+63],[x+113,x+w+9]]){rect(g,a,y+h+18,z-a,2,'#eeeede');rect(g,a,y+h+29,z-a,2,'#eeeede');for(let xx=a;xx<z;xx+=6)rect(g,xx,y+h+13,2,24,'#f1f0df');}
}
function drawCulture(g,b){
 const x=b.x,y=b.y+b.h-218,w=b.w;
 shadow(g,x+w/2,y+222,w*.66);
 // Tall cream frontage, salmon plinth, recessed central entrance and white rails.
 poly(g,[[x+w,y],[x+w+19,y+15],[x+w+19,y+215],[x+w,y+218]],'#c5bda3','#827966');
 rect(g,x,y,w,218,'#eee9d7','#a79c80');rect(g,x,y+199,w,19,'#bd8164');
 rect(g,x+7,y,9,199,'#d6c8a6');rect(g,x+w-14,y,8,199,'#d6c8a6');
 for(const yy of [y+19,y+88,y+157])for(const xx of [x+24,x+62,x+101])windowBox(g,xx,yy,25,36);
 rect(g,x+61,y+170,28,44,'#485959','#fff5dd');
 poly(g,[[x+48,y+165],[x+94,y+165],[x+102,y+171],[x+43,y+171]],'#b6a280','#746e5b');
 for(const yy of [y+57,y+126]){rect(g,x+59,yy,34,2,'#fffdf0');rect(g,x+59,yy+9,34,2,'#fffdf0');for(let xx=x+59;xx<=x+93;xx+=8)rect(g,xx,yy-11,2,23,'#fffdf0');}
 text(g,'KULTÚRNY',x+35,y+73,7,'#967039');text(g,'DOM',x+35,y+82,7,'#967039');text(g,'KULTÚRHÁZ',x+106,y+77,8,'#967039');
 for(const xx of [x+47,x+91]){rect(g,xx,y+38,1,26,'#877963');poly(g,[[xx,y+40],[xx+9,y+43],[xx+7,y+58],[xx,y+54]],xx<x+60?'#a35c52':'#65849b');}
 // Fence leaves a walk-through gap aligned with the door.
 for(const [a,z] of [[x-15,x+51],[x+97,x+w+22]]){rect(g,a,y+240,z-a,3,'#eeeede');rect(g,a,y+229,z-a,2,'#faf8e9');for(let xx=a;xx<z;xx+=7)rect(g,xx,y+219,2,28,'#f9f7e8');}
 for(const xx of [x+15,x+w-9]){ellipse(g,xx,y+210,12,9,'#789253');ellipse(g,xx-3,y+205,3,3,'#e3ae98');}
}
function drawRecycling(g,b,i){
 const used=state&&state.time<(state.bins[i]||0),glass=b.material==='glass';
 g.save();g.translate(b.x,b.y);shadow(g,0,2,34);
 if(glass){poly(g,[[-32,0],[-27,-66],[-19,-75],[23,-75],[32,-64],[33,0]],'#648563','#35523c');rect(g,-29,-5,60,7,'#526f50');for(const x of [-15,17]){ellipse(g,x,-58,7,9,'#263d30');ellipse(g,x,-59,4,6,'#172d24');}ellipse(g,0,-80,5,5,'#879282');rect(g,-10,-34,20,17,'#e7e8d5');text(g,'ÜVEG',0,-23,7,'#375039');}
 else{const c=b.material==='paper'?'#397bd0':'#d6b64d';rect(g,-31,-57,62,54,c,'#37505b');poly(g,[[31,-57],[39,-64],[39,-11],[31,-3]],b.material==='paper'?'#2b60a0':'#ae9038');rect(g,-31,-65,63,10,c,'#37505b');rect(g,-26,-56,52,9,'#24382f');poly(g,[[-34,-66],[-24,-73],[34,-73],[37,-65]],b.material==='paper'?'#609ae4':'#e7cf74','#455c55');for(const x of [-25,24]){rect(g,x-4,-3,8,7,'#3f4b40');ellipse(g,x,5,5,5,'#273b32');}rect(g,-22,-36,44,17,'#eae9d4');text(g,b.material==='paper'?'PAPÍR':'MŰANYAG',0,-24,8,'#405347');}
 if(used)text(g,'·',0,-9,17,'#f1eed5');g.restore();
}
function drawBuilding(g,b){if(b.type==='office'){drawOffice(g,b);return;}if(b.type==='culture'){drawCulture(g,b);return;}const{x,y,w,h,type}=b;shadow(g,x+w/2,y+h,w*.6);rect(g,x,y+15,w,h-15,type==='castle'?'#e1bf6b':type==='shop'?'#e3dfca':type==='culture'?'#d5b78a':'#d5c59c','#71674d');poly(g,[[x+w,y+15],[x+w+14,y+1],[x+w+14,y+h-14],[x+w,y+h]],'#b4a77d');
 if(type==='shop'){rect(g,x-5,y-20,w+10,48,'#e6e4d4','#858775');rect(g,x,y+29,w,27,'#c77954');for(let xx=x+15;xx<x+w-95;xx+=48) {rect(g,xx,y+34,40,17,'#283a38','#cbbb9d');text(g,'coop',xx+20,y+46,8,'#cf7657');}rect(g,x+w-92,y+57,76,h-57,'#ae633f');windowBox(g,x+w-83,y+65,58,h-68);rect(g,x+w-84,y+70,27,18,'#dec06c');rect(g,x+w-52,y+100,21,24,'#e6d6a7');rect(g,x+w-103,y+15,107,17,'#c48159','#885c43');rect(g,x+151,y-11,153,28,'#bb653e');rect(g,x+121,y-11,30,28,'#f2eee0');text(g,'coop',x+136,y+7,10,'#a94933');text(g,'SUPERMARKET',x+227,y+9,17,'#fff4d8');rect(g,x+15,y+105,31,70,'#b3b5a3');windowBox(g,x+19,y+112,24,62);text(g,'COOP JEDNOTA',x+w-53,y+49,8,'#f5ead7');
 for(let i=0;i<9;i++){g.strokeStyle='#777e70';g.lineWidth=2;g.beginPath();g.ellipse(x+210+i*13,y+h+5,6,12,0,Math.PI,Math.PI*2);g.lineTo(x+216+i*13,y+h+17);g.stroke();}rect(g,x+w+20,y+h-18,17,26,'#4f7890','#355263');
 }else if(type==='castle'){for(let xx=x+25;xx<x+w;xx+=52){windowBox(g,xx,y+46,25,35);windowBox(g,xx,y+103,25,42);}poly(g,[[x-14,y+18],[x+30,y-47],[x+w-25,y-47],[x+w+13,y+18]],'#94563b','#684a33');for(let yy=y-35;yy<y+18;yy+=10){g.strokeStyle='#6f47344d';g.beginPath();g.moveTo(x+20,yy);g.lineTo(x+w-15,yy);g.stroke();}rect(g,x+w/2-42,y+10,84,h-10,'#edd193','#9f874d');poly(g,[[x+w/2-48,y+10],[x+w/2,y-27],[x+w/2+48,y+10]],'#e3c384','#866c42');windowBox(g,x+w/2-15,y+35,30,39);rect(g,x+w/2-20,y+h-59,40,59,'#665b3c','#f3dba5');for(const xx of [x,x+w-36]){rect(g,xx,y+25,36,125,'#d9b66c');windowBox(g,xx+9,y+40,18,29);windowBox(g,xx+9,y+90,18,35);}text(g,'KÁLNOKY',x+w/2,y+97,10,'#77532f');
 }else{windowBox(g,x+18,y+63,49,51);windowBox(g,x+w-65,y+63,49,51);rect(g,x+w/2-18,y+70,36,h-70,'#546352','#e5d4ad');poly(g,[[x-12,y+30],[x+28,y-30],[x+w-26,y-30],[x+w+12,y+30]],type==='culture'?'#a36140':'#965e42','#684d37');for(let yy=y-20;yy<y+30;yy+=11){g.strokeStyle='#e4a46745';g.beginPath();g.moveTo(x+23,yy);g.lineTo(x+w-18,yy);g.stroke();}if(['culture','school','restaurant'].includes(type)){rect(g,x+38,y+26,w-76,24,'#456448','#283e31');text(g,type==='school'?'ISKOLA':type==='restaurant'?'LION VENDÉGLŐ':'KULTÚRHÁZ',x+w/2,y+44,Math.min(12,w/12));rect(g,x-20,y+h-29,29,27,'#8c673c');ellipse(g,x-4,y+h-29,10,6,'#ce8459');}}
}
function drawShelter(g,caption='PARLAMENT'){const x=533,y=850;shadow(g,655,1020,137);for(const xx of [x+8,x+213])rect(g,xx,y+49,10,114,'#8b5935','#604931');rect(g,x+16,y+132,196,12,'#a37140','#684a2f');rect(g,x+16,y+124,196,6,'#c2955b');rect(g,x+30,y+116,14,46,'#805334');rect(g,x+189,y+116,14,46,'#805334');rect(g,x+27,y+84,171,29,'#ba8750','#684a2f');for(let xx=x+38;xx<x+193;xx+=20)rect(g,xx,y+84,1,29,'#805f3a');rect(g,x+52,y+110,11,49,'#805334');rect(g,x+160,y+110,11,49,'#805334');bottle(g,x+105,y+83,.8);orc(g,x+175,y+162,-1,0,false,.8);for(const xx of [x+2,x+222])rect(g,xx,y+48,13,124,'#a87542','#684a2f');poly(g,[[x-24,y+53],[x+102,y-10],[x+260,y+53],[x+246,y+81],[x+102,y+18],[x-11,y+80]],'#5e6256','#453e2b');poly(g,[[x-24,y+53],[x+102,y-10],[x+260,y+53],[x+250,y+63],[x+102,y+2],[x-17,y+65]],'#b07a44','#64482f');for(let yy=0;yy<3;yy++){g.strokeStyle='#a4a38a30';g.beginPath();g.moveTo(x+35-yy*20,y+25+yy*12);g.lineTo(x+192+yy*18,y+25+yy*12);g.stroke();}rect(g,x+42,y+42,147,29,'#d1a76b','#694a2b');text(g,caption,x+115,y+63,17,'#403426');}
function bottle(g,x,y,s=1){g.save();g.translate(x,y);g.scale(s,s);shadow(g,0,2,8);rect(g,-5,-17,10,18,'#416b48','#223f30');rect(g,-2,-24,4,8,'#62804b');rect(g,-2,-25,4,3,'#b9a45f');rect(g,-4,-12,8,7,'#e1d2a0');rect(g,-3,-18,2,7,'#9dad7780');g.restore();}
function bicycle(g,x,y,scale=1){g.save();g.translate(x,y);g.scale(scale,scale);shadow(g,0,0,35);for(const wx of [-25,25]){g.strokeStyle='#333f36';g.lineWidth=3;g.beginPath();g.arc(wx,-9,17,0,Math.PI*2);g.stroke();g.strokeStyle='#b3b6a0';g.lineWidth=1;for(let a=0;a<Math.PI*2;a+=Math.PI/4){g.beginPath();g.moveTo(wx,-9);g.lineTo(wx+Math.cos(a)*16,-9+Math.sin(a)*16);g.stroke();}}g.strokeStyle='#9e6346';g.lineWidth=3;g.beginPath();g.moveTo(-25,-9);g.lineTo(-9,-35);g.lineTo(2,-9);g.lineTo(-25,-9);g.moveTo(-9,-32);g.lineTo(17,-32);g.lineTo(2,-9);g.lineTo(25,-9);g.lineTo(14,-44);g.lineTo(23,-46);g.stroke();rect(g,-17,-39,15,4,'#414738');rect(g,-36,-31,18,3,'#636f59');g.restore();}
function orc(g,x,y,face=1,step=0,riding=false,scale=1){g.save();g.translate(x,y);g.scale(scale,scale);shadow(g,0,0,20);if(state?.boost>0&&scale===1){g.strokeStyle='#ead574';g.lineWidth=2;g.beginPath();g.ellipse(0,-20,27+Math.sin(clock*9)*2,36,0,0,Math.PI*2);g.stroke();}if(riding)bicycle(g,0,0,.85);const walk=Math.sin(step)*3;rect(g,-12,-20,10,19+walk,'#354e5a','#263b39');rect(g,3,-20,10,19-walk,'#354e5a','#263b39');ellipse(g,-8,walk,8,4,'#473c2e');ellipse(g,9,-walk,8,4,'#473c2e');ellipse(g,0,-31,18,20,'#809646');poly(g,[[-12,-47],[10,-47],[16,-23],[-16,-23]],'#ddd5b1','#767e4f');g.strokeStyle='#c1bba0';g.lineWidth=1;g.beginPath();g.moveTo(-7,-40);g.lineTo(3,-26);g.stroke();ellipse(g,-18,-29+walk,5,12,'#809646');ellipse(g,18,-29-walk,5,12,'#809646');poly(g,[[-14,-63],[-26,-67],[-18,-52]],'#829e4b','#485f37');poly(g,[[14,-63],[25,-67],[18,-52]],'#829e4b','#485f37');ellipse(g,0,-60,17,19,'#8da850');ellipse(g,-4,-67,12,10,'#a2b762');ellipse(g,face*12,-57,8,6,'#8ba345');rect(g,-11,-67,8,3,'#3d4c2f');rect(g,3,-67,8,3,'#3d4c2f');ellipse(g,-7,-62,2,2,'#f1de93');ellipse(g,7,-62,2,2,'#f1de93');poly(g,[[-10,-49],[-9,-57],[-5,-48]],'#f4e5b6');poly(g,[[7,-49],[11,-57],[12,-48]],'#f4e5b6');g.strokeStyle='#415834';g.lineWidth=2;g.beginPath();g.moveTo(-7,-47);g.lineTo(7,-47);g.stroke();poly(g,[[-12,-75],[-7,-83],[-1,-77],[4,-82],[9,-75]],'#414a2b');if(!riding){rect(g,20,-20,15,20,'#c0b18a','#756d4b');g.strokeStyle='#b5aa82';g.beginPath();g.arc(27,-21,5,Math.PI,0);g.stroke();}g.restore();}
function statue(g,x,y,n){shadow(g,x,y,20);rect(g,x-16,y-10,32,13,'#a39774','#736b4e');poly(g,[[x-10,y-10],[x-13,y-58],[x-8,y-75],[x+9,y-75],[x+14,y-54],[x+10,y-10]],'#806039','#4e4830');ellipse(g,x,y-81,11,15,'#9c7647');poly(g,[[x-12,y-88],[x,y-104],[x+12,y-88]],'#675737','#493e29');rect(g,x-20,y-65,4,61,'#594b30');g.strokeStyle='#baa071';g.lineWidth=2;g.beginPath();g.moveTo(x-5,y-52);g.lineTo(x+6,y-45);g.lineTo(x+2,y-16);g.stroke();text(g,['ÁLMOS','ELŐD','OND','KOND','TAS','HUBA','TÖHÖTÖM'][n],x,y+14,8,'#263f2e');}
function well(g){const x=P.well.x,y=P.well.y;shadow(g,x,y,34);ellipse(g,x,y,32,15,'#c7c5ae');ellipse(g,x,y-7,27,13,'#9fa28e');ellipse(g,x,y-9,21,9,'#557f79');rect(g,x-5,y-55,10,46,'#577d76','#365850');g.strokeStyle='#779c8e';g.lineWidth=7;g.beginPath();g.moveTo(x,y-49);g.lineTo(x+19,y-49);g.lineTo(x+19,y-37);g.stroke();g.strokeStyle='#b6d9cc';g.lineWidth=2;g.beginPath();g.moveTo(x+19,y-37);g.lineTo(x+18+Math.sin(clock*4),y-12);g.stroke();}
function drawBin(g,b,i){if(b.type==='recycling'){drawRecycling(g,b,i);return;}const blue=b.type==='blue',brown=b.type==='brown',scale=blue?1.4:brown?1:1;g.save();g.translate(b.x,b.y);g.scale(scale,scale);shadow(g,0,0,18);const used=state&&state.time<(state.bins[i]||0);const color=blue?'#477b9d':brown?'#896042':'#476c55';rect(g,-14,-32,28,32,used?'#74796a':color,'#314b3b');poly(g,[[-17,-33],[-12,-39],[16,-39],[17,-32]],used?'#89917e':blue?'#6b99b4':brown?'#a67a51':'#6f8a65','#314b3b');rect(g,-8,-2,5,6,'#334334');rect(g,6,-2,5,6,'#334334');if(!blue)text(g,brown?'BIO':used?'·':'↻',0,-11,brown?9:17,'#e0ddba');g.restore();}
function render(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);if(!state){state=fresh();camera={x:state.x-width/2,y:state.y-height/2};}const g=ctx;g.save();g.translate(-Math.round(camera.x),-Math.round(camera.y));g.drawImage(floor,0,0);for(const l of locations){if(l.id==='park'||l.id==='lion')continue;g.strokeStyle='#f4df9b35';g.setLineDash([4,5]);g.lineWidth=2;g.beginPath();g.ellipse(l.x,l.y,30,14,0,0,Math.PI*2);g.stroke();g.setLineDash([]);}
 const objects=[];for(const b of buildings)objects.push({y:b.y+b.h,draw:()=>{if(b.type==='shop'||b.type==='castle'){g.save();g.translate(b.x,b.y);g.scale(b.w/(b.type==='shop'?460:360),b.h/(b.type==='shop'?190:185));drawBuilding(g,{...b,x:0,y:0,w:b.type==='shop'?460:360,h:b.type==='shop'?190:185});g.restore();}else drawBuilding(g,b);}});for(const t of trees)objects.push({y:t.y,draw:()=>{if(t.y>state.y&&t.y-state.y<115&&Math.abs(t.x-state.x)<55)g.globalAlpha=.42;drawTree(g,t);}});for(const id of MAP.shelters){const q=P[id];objects.push({y:q.y+25,draw:()=>{g.save();g.translate(q.x-650*.53,q.y-945*.53);g.scale(.53,.53);drawShelter(g,id==='parliament'?'PARLAMENT':'KIÜLŐ');g.restore();}});}objects.push({y:P.well.y,draw:()=>well(g)});bins.forEach((b,i)=>objects.push({y:b.y,draw:()=>drawBin(g,b,i)}));
 for(let i=0;i<7;i++){const x=P.park.x,y=P.park.y-54+i*18;objects.push({y,draw:()=>{g.save();g.translate(x,y);g.scale(.52,.52);statue(g,0,0,i);g.restore();}});}
 for(const it of groundItems){if(state.taken.includes(it.id))continue;objects.push({y:it.y,draw:()=>{if(it.type==='bottle'){bottle(g,it.x,it.y,.85);if(Math.sin(clock*2+it.id)>0.7)text(g,'✦',it.x+10,it.y-22,12,'#fff4c6');}else if(it.type==='butt'){g.save();g.translate(it.x,it.y);g.rotate(-.35);rect(g,-6,-4,12,5,'#eee3c7','#7e7857');rect(g,-6,-4,4,5,'#bf8550');g.restore();}else{ellipse(g,it.x,it.y-5,18+Math.sin(clock*4)*3,9,'#d7d77955');bottle(g,it.x,it.y,1.2);text(g,'✦',it.x,it.y-40+Math.sin(clock*3)*4,23,'#f6e184');}}});}
 if(!state.bike)objects.push({y:state.bikeY,draw:()=>bicycle(g,state.bikeX,state.bikeY)});
 objects.push({y:boar.y,draw:()=>{shadow(g,boar.x,boar.y,21);ellipse(g,boar.x,boar.y-12,22,12,'#685442');ellipse(g,boar.x+20,boar.y-11,10,8,'#82664a');rect(g,boar.x-12,boar.y-6,5,10,'#4e4435');rect(g,boar.x+8,boar.y-6,5,10,'#4e4435');poly(g,[[boar.x+19,boar.y-4],[boar.x+25,boar.y-13],[boar.x+28,boar.y-4]],'#ded3ab');}});
 objects.push({y:state.y,draw:()=>orc(g,state.x,state.y,state.facing||1,state.steps,state.bike)});objects.sort((a,b)=>a.y-b.y);for(const o of objects){g.save();o.draw();g.restore();}
 for(const l of locations)if(dist(state,l)<420)label(g,l.name,l.x,l.y+38);for(const b of MAP.busStops){rect(g,b.x-2,b.y-37,4,38,'#667568');rect(g,b.x-14,b.y-54,28,22,'#5b8eb0','#e0e3c7');text(g,'BUS',b.x,b.y-38,9,'#fff6da');}if(near&&!dialog){g.strokeStyle='#fae2a0';g.lineWidth=2;g.beginPath();g.ellipse(near.x,near.y+4,22,9,0,0,Math.PI*2);g.stroke();}if(keys.shift&&state.energy<100){rect(g,state.x-21,state.y+15,42,4,'#243d2c');rect(g,state.x-21,state.y+15,42*state.energy/100,4,'#eac56d');}g.restore();const vignette=g.createRadialGradient(width/2,height/2,height*.25,width/2,height/2,width*.75);vignette.addColorStop(0,'#12251c00');vignette.addColorStop(1,'#12251c33');g.fillStyle=vignette;g.fillRect(0,0,width,height);}
function resize(){width=innerWidth;height=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;update(dt);render();requestAnimationFrame(frame);}
window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(!running)return;if(e.repeat){if(!dialog)keys[k]=true;return;}if(k==='escape'){dialog?close():pause();return;}if(dialog){if(k==='tab'){const controls=[...$('modal').querySelectorAll('button:not(:disabled)')];const at=controls.indexOf(document.activeElement);e.preventDefault();controls[(at+(e.shiftKey?-1:1)+controls.length)%controls.length]?.focus();}return;}keys[k]=true;if(k==='e'||k===' ')interact();if(k==='b')bike();if(k==='m')map();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{keys={};save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};save();if(running&&!dialog)pause();}});
 $('newGame').onclick=()=>{if(load()){resetDialog();}else start(fresh());};$('continueGame').hidden=!load();$('continueGame').onclick=()=>start(load());$('closeModal').onclick=close;$('pauseButton').onclick=pause;$('mapButton').onclick=map;$('interactButton').onclick=interact;$('touchBike').onclick=bike;$('soundButton').onclick=()=>{sound=!sound;$('soundButton').innerHTML='♪ <span>Hang: '+(sound?'be':'ki')+'</span>';$('soundButton').setAttribute('aria-label','Hang '+(sound?'kikapcsolása':'bekapcsolása'));beep();};
 document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});const off=()=>keys[b.dataset.key]=false;b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('lostpointercapture',off);});
 resize();requestAnimationFrame(frame);
 // Read-only inspection hook for smoke tests and local diagnostics.
 window.csicsoGame={snapshot:()=>JSON.parse(JSON.stringify({state,dialog,near,locations,bins,groundItems,width:W,height:H})),isBlocked:blocked};
})();
